name: Lint & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["lts/*"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: lint
        run: |
          yarn lint

      #
      # Package
      #

      - name: package:typecheck
        run: |
          yarn workspace @servicejs-private/modules run typecheck
      - name: package:test
        run: |
          yarn workspace @servicejs-private/modules run test
      - name: package:build
        run: |
          yarn workspace @servicejs-private/modules run build

      #
      # Examples
      #

      # basic

      - name: example:basic:typecheck
        run: |
          yarn workspace example-basic run typecheck
      - name: example:basic:test
        run: |
          yarn workspace example-basic run test
      - name: example:basic:build
        run: |
          yarn workspace example-basic run build
      - name: example:basic:start
        run: |
          yarn workspace example-basic run start
